[package]
name = "zorua"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.14"
aligned = "0.4.1"
ux2 = "0.8.5"
